### ISSUE TITLE
View other users' profiles

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#10]
**Background Information:**

Currently, the application does not have a feature that allows users to view other users' profiles. This can limit the user experience and make it difficult for users to find and interact with other users on the platform. In order to provide a better user experience and increase user engagement, we need to implement a feature that allows users to view other users' profiles.

**Requirements:**

- Retrieve user profile information, including username, bio, and profile picture, from the database.
- Create a custom layout for the user profile screen that displays the retrieved information.
- Implement logic to handle user input for navigating to other users' profiles.
- Integrate the user profile feature with the existing codebase to handle user profile retrieval and display.

**Expected Outcome:**

Once users are able to view other users' profiles, the application will provide a better user experience and increase user engagement. This will make it easier for users to find and interact with other users on the platform, leading to increased user retention and satisfaction.

**Comment by vardhinialuru** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
