### ISSUE TITLE
Allow user to reply to other users' tweets

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#11]
**Background Information:**

Currently, the application does not have a feature that allows users to reply to other users' tweets on the platform. This can limit the user experience and make it difficult for users to engage in conversations with other users. In order to provide a better user experience and increase user engagement, we need to implement a feature that allows users to reply to other users' tweets.

**Requirements:**

- Implement a feature that allows users to reply to other users' tweets by clicking a reply button on the tweet.
- Create a custom layout for the reply button that opens a reply modal or screen.
- Integrate the reply feature with the existing codebase to handle user input and update the database with the new reply information.
- Implement validation logic to ensure that the reply text meets size and format requirements.

**Expected Outcome:**

Once users are able to reply to other users' tweets on the platform, the application will provide a better user experience and increase user engagement. This will make it easier for users to engage in conversations with other users, leading to increased user retention and satisfaction.

**Comment by vardhinialuru** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
