### ISSUE TITLE
Allow user to search for other users

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#12]
**Background Information:**

Currently, the application does not have a feature that allows users to search for other users on the platform. This can limit the user experience and make it difficult for users to find and follow other users they are interested in. In order to provide a better user experience and increase user engagement, we need to implement a feature that allows users to search for other users.

**Requirements:**

- Implement a feature that allows users to search for other users by entering a username or display name in the search bar.
- Create a custom layout for the search bar that displays search results in a list view.
- Integrate the search feature with the existing codebase to handle user input and update the search results in real-time.
- Implement validation logic to ensure that the search query meets size and format requirements.

**Expected Outcome:**

Once users are able to search for other users on the platform, the application will provide a better user experience and increase user engagement. This will make it easier for users to find and follow other users they are interested in, leading to increased user retention and satisfaction.

**Comment by snehanjaligvs** [comment]
Please assign me this
