### ISSUE TITLE
Allow user to create a new tweet with images

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#13]
**Background Information:**

Currently, the application does not allow users to include images in their tweets. This limits the type of content that users can share on the platform. In order to provide a better user experience and allow for richer content creation, we need to allow users to create tweets that include images.

**Requirements:**

- Implement a feature that allows users to select and upload images from their device.
- Create a custom layout for the new tweet creation screen that includes the option to add images.
- Integrate the image upload feature with the existing codebase to handle image uploads.
- Implement validation logic to ensure that uploaded images meet size and format requirements.

**Expected Outcome:**

Once users are able to create tweets that include images, the application will provide a better user experience and allow for richer content creation. This will make the application more versatile and increase user engagement, leading to increased user retention and satisfaction.

**Comment by snehanjaligvs** [comment]
Please assign me this
