### ISSUE TITLE
Allow user to edit their own profile

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#14]
**Background Information:**

Currently, the application does not have a feature that allows users to edit their own profile information. This can limit the user experience and make it difficult for users to update their profile information or correct errors. In order to provide a better user experience and increase user engagement, we need to implement a feature that allows users to edit their own profile.

**Requirements:**

- Implement a feature that allows users to update their profile information, including their username, bio, and profile picture.
- Create a custom layout for the edit profile screen that includes the fields for updating profile information.
- Integrate the edit profile feature with the existing codebase to handle user input and update the database with the new profile information.
- Implement validation logic to ensure that updated profile information meets size and format requirements.

**Expected Outcome:**

Once users are able to edit their own profile information, the application will provide a better user experience and increase user engagement. This will make it easier for users to update their profile information or correct errors, leading to increased user retention and satisfaction.

**Comment by snehanjaligvs** [comment]
Please assign me this
