### ISSUE TITLE
Implement like button animation

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#15]
**Background Information:**

Currently, the application lacks an animation for the like button. This can make the application feel static and unresponsive to user input. In order to provide a better user experience, we need to implement an animation for the like button.

**Requirements:**

- Create a custom animation for the like button.
- Integrate the animation with the existing codebase to handle user input for the like button.
- Implement logic to handle like button input and trigger the animation.

**Expected Outcome:**

Once the animation for the like button is implemented, the application will provide better user feedback and be more responsive to user input. This will improve the overall user experience and make the application more enjoyable to use.

**Comment by snehanjaligvs** [comment]
Please assign me this
