### ISSUE TITLE
Set up user authentication controller

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#16]
**Background Information:**

Currently, the project lacks a user authentication controller. This is causing security vulnerabilities in the application as anyone can access the protected routes without any authentication. In order to resolve this issue, we need to set up a user authentication controller.

**Requirements:**

- Create a user authentication controller using a secure authentication protocol like OAuth2.0 or JWT.
- Integrate the user authentication controller with the existing project codebase to protect the routes that require authentication.
- Configure the user authentication controller to interact with the database to store and retrieve user credentials.
- Implement password reset and email verification features in the user authentication controller.

**Expected Outcome:**

Once the user authentication controller is set up, the application will be more secure and only authenticated users will be able to access the protected routes. This will improve the overall user experience and protect the application from unauthorized access.

**Comment by snehanjaligvs** [comment]
Please assign me this
