### ISSUE TITLE
View home screen with a feed of tweets from people they follow

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#17]
**Background Information:**

Currently, the application does not have a home screen that displays a feed of tweets from people that the user follows. This can make it difficult for users to stay up-to-date with the tweets of the people they follow. In order to provide a better user experience and improve user engagement, we need to create a home screen that displays a feed of tweets from people the user follows.

**Requirements:**

- Retrieve the list of people that the user follows from the database.
- Retrieve the tweets of the people that the user follows from the database.
- Create a custom layout for the home screen that displays the tweets from the people that the user follows.
- Implement logic to handle user input for refreshing the feed and displaying additional tweets.

**Expected Outcome:**

Once the home screen is created and displays a feed of tweets from the people that the user follows, the application will provide a better user experience and increase user engagement. This will make it easier for users to stay up-to-date with the tweets of the people they follow, leading to increased user retention and satisfaction.

**Comment by vardhinialuru** [comment]
Please assign me this.
