### ISSUE TITLE
Implement real-time updates for tweets and likes

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#18]
**Background Information:**

Currently, the application does not support real-time updates for tweets and likes. This means that users have to manually refresh the page to see the latest tweets and likes. In order to provide a better user experience, we need to implement real-time updates for tweets and likes.

**Requirements:**

- Set up a real-time messaging system using a library like Pusher or Socket.IO.
- Integrate the real-time messaging system with the existing codebase to send updates to the clients in real-time.
- Implement logic to handle real-time updates for tweets and likes and display them to the users without requiring a page refresh.

**Expected Outcome:**

Once real-time updates for tweets and likes are implemented, users will be able to see the latest tweets and likes without having to manually refresh the page. This will provide a better user experience and make the application more interactive.

**Comment by abhinavpingali** [comment]
Please assign me this
