### ISSUE TITLE
Make UI using figma for login and home screen

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#19]
## Objective

Design a user interface for the login and home screens using Figma.

## Requirements

- Color scheme: Use the company's primary colors of blue (#0071C5) and green (#6DBCDB) for the login and home screens respectively.
- Typography: Use the Open Sans font for all text.
- Layout: The login screen should have a centered login form with input fields for email and password. The home screen should have a navigation bar at the top with links to different sections of the app, and a section for recent activity.

## Deliverables

- A Figma file with the designed UI for the login and home screens.
- Any design assets or elements used in the UI.

## Constraints

- The UI design should be responsive and work well on different devices and screen sizes.
- The design should be accessible and comply with WCAG 2.1 Level AA standards.
- The design should be compatible with both iOS and Android devices.

## Timeline

The UI design work should be completed by April 15, 2023.

## Assignee

The issue is assigned to @username.

**Comment by kaushmani** [comment]
Please assign me this.
