### ISSUE TITLE
Make UI using figma for notification and sidebar screen

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#20]
## Objective

Design a user interface for the notification and sidebar screens using Figma.

## Requirements

- Color scheme: Use the company's primary color of purple (#8C4EFF) for both screens.
- Typography: Use the Montserrat font for all text.
- Layout: The notification screen should display a list of recent notifications with the most recent at the top. The sidebar screen should have a navigation menu with links to different sections of the app.

## Deliverables

- A Figma file with the designed UI for the notification and sidebar screens.
- Any design assets or elements used in the UI.

## Constraints

- The UI design should be responsive and work well on different devices and screen sizes.
- The design should be accessible and comply with WCAG 2.1 Level AA standards.
- The design should be compatible with both iOS and Android devices.

## Timeline

The UI design work should be completed by April 30, 2023.

## Assignee

The issue is assigned to @username.

**Comment by kaushmani** [comment]
Please assign me this.
