### ISSUE TITLE
Provide proper class and dependency injection for the application

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#4]
## Purpose and Background
The purpose of this issue is to provide proper class and dependency injection for our Flutter application using Appwrite. This will enable us to better organize our code and make it more modular, improving maintainability and scalability.

## Scope of the Issue
This issue requires the following tasks to be completed:
- Analyze the current codebase and identify opportunities for refactoring and dependency injection.
- Implement dependency injection using a framework such as Provider or GetIt.
- Reorganize the codebase to use classes and interfaces where appropriate.

## Acceptance Criteria
- The codebase should be refactored to use dependency injection.
- Dependencies should be properly managed and injected throughout the codebase.
- The application should compile and run without any errors related to dependency injection.

## Dependencies
- Flutter 2.5.2
- Appwrite 0.8.2
- Provider 6.0.0 or GetIt 7.2.0

## Testing
To test the changes, we will run unit tests to ensure that the codebase is properly organized and dependencies are injected correctly.

## Deadline
This issue should be completed by May 1st.

## Additional Information
We are using Flutter for the application and Appwrite for user authentication and data management. Resources that may be helpful include:
- Provider documentation: [link to Provider documentation](https://pub.dev/packages/provider)
- GetIt documentation: [link to GetIt documentation](https://pub.dev/packages/get_it)
- Appwrite documentation: [link to Appwrite documentation](https://appwrite.io/docs)

**Comment by abhinavpingali** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
