### ISSUE TITLE
Enable user to log in using previously created credentials

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#5]
**Background Information:**

Currently, the application does not allow users to log in using previously created credentials. This can be inconvenient for users who have already signed up with the application and need to log in again. In order to provide a better user experience, we need to enable users to log in using their previously created credentials.

**Requirements:**

- Create a log-in form for users to input their previously created credentials.
- Implement validation logic to ensure that email addresses and passwords are correct.
- Integrate the log-in form with the existing codebase to handle user log-ins.
- Implement a session management system to maintain user sessions and allow for secure log-ins.

**Expected Outcome:**

Once users are able to log in using their previously created credentials, the application will provide a more convenient sign-in process and improve the overall user experience. This will make the application more user-friendly and increase user retention.

**Comment by abhinavpingali** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
