### ISSUE TITLE
Allow user to like tweets

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#6]
**Background Information:**

Currently, the application does not have a feature that allows users to like tweets on the platform. This can limit the user experience and make it difficult for users to interact with the tweets they find interesting or agree with. In order to provide a better user experience and increase user engagement, we need to implement a feature that allows users to like tweets.

**Requirements:**

- Implement a feature that allows users to like tweets by clicking a heart icon on the tweet.
- Create a custom layout for the heart icon that includes the like/unlike toggle button.
- Integrate the like feature with the existing codebase to handle user input and update the database with the new like information.
- Implement validation logic to ensure that users cannot like the same tweet multiple times.

**Expected Outcome:**

Once users are able to like tweets on the platform, the application will provide a better user experience and increase user engagement. This will make it easier for users to interact with tweets they find interesting or agree with, leading to increased user retention and satisfaction.

**Comment by abhinavpingali** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
