### ISSUE TITLE
Allow new users to sign up with email and password

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#7]
**Background Information:**

Currently, the application does not allow new users to sign up with email and password. This limits the user base of the application as users are required to sign up with third-party services. In order to expand the user base and provide a more convenient sign-up process, we need to allow new users to sign up with email and password.

**Requirements:**

- Create a sign-up form for new users to input their email and password.
- Implement validation logic to ensure that email addresses are valid and passwords are strong and secure.
- Integrate the sign-up form with the existing codebase to handle new user sign-ups.
- Implement a verification email to confirm new user email addresses.

**Expected Outcome:**

Once new users are able to sign up with email and password, the application will have a larger potential user base and provide a more convenient sign-up process. This will improve the overall user experience and make the application more accessible to a wider audience.

**Comment by snehanjaligvs** [comment]
Please assign me this
