### ISSUE TITLE
Store user data and tweets in the Appwrite database and storage

### ISSUE THREAD

**Issue by aaqilrk** [aaqilrk/twitter-clone#9]
**Background Information:**

Currently, the application is not properly storing user data and tweets. This can lead to data loss or security vulnerabilities. In order to improve the data management of the application, we need to store user data and tweets in the Appwrite database and storage.

**Requirements:**

- Set up the Appwrite server to handle the database and storage.
- Migrate the existing user data and tweets to the Appwrite database and storage.
- Integrate the Appwrite database and storage with the existing codebase to handle user data and tweets.
- Implement logic to retrieve and store user data and tweets from the Appwrite database and storage.

**Expected Outcome:**

Once user data and tweets are stored in the Appwrite database and storage, the application will have better data management and improved security. This will ensure that user data is properly stored and can be easily accessed and retrieved when needed.

**Comment by vardhinialuru** [comment]
Please assign me this

**Comment by aaqilrk** [comment]
Okay sure
